### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by gulping** [akim-mcmath/ejs-html-loader#16]
I'm using this loader with webpack 4, and it works.

some warnings are showed.
```
warning " > ejs-html-loader@3.1.0" has unmet peer dependency "webpack@2.x - 3.x".
warning " > ejs-html-loader@3.1.0" has unmet peer dependency "ejs@2.x".
```

it may be resolved with just update dependencies in package.json

**Comment by gulping** [comment]
@mcmath no pulse?

**Comment by bdwain** [comment]
bump @mcmath any plans to support webpack 4?

**Comment by rowild** [comment]
I second this! I use it in WP 4 and it works fine so far. Please update the dependencies if not anything else! Thanks!

**Comment by rowild** [comment]
Thank you, McMath! 👍
