### ISSUE TITLE
Pass Different Variables to Each Page of a Multi-Page Application

### ISSUE THREAD

**Issue by daniel-nagy** [akim-mcmath/ejs-html-loader#9]
This is more of a question than an issue.

I have a multi-page application where each page uses the same `index.ejs` file. Each page needs to include a different javascript file and possibly an `ng-app` attribute.

```html
// index.ejs (simplified version)
<!DOCTYPE html>
<html lang="en" ng-app="<%=page%>">

  <head>
    <link href="app.css" rel="stylesheet" type="text/css">
    <link href="<%=page%>.css" rel="stylesheet" type="text/css">
  </head>

  <body>

    <%- include('header.html') %>
    <%- include(page + '.html') %>
    <%- include('footer.html') %>
  
    <script src="app.js" type="text/javascript"></script>
    <script src="<%=page%>.js" type="text/javascript"></script>

  </body>

</html>
```

The question is, how can I pass a different page variable to each require call to `index.ejs`?

My Webpack config is something like

```javascript
const ejsLoader = {
  loader: 'ejs-html-loader',
  options: {
    page: '', // I can only make this a static value?
    production: Boolean(env.production)
  }
};

const ejsRule = {
  include: 'index.ejs',
  test: 'index.ejs',
  use: (() => {
    if (env.production) {
      return plugins.extractHtml.extract({
        allChunks: true,
        publicPath: BUILD,
        use: ['raw-loader', ejsLoader]
      });
    }

    return [ejsLoader];
  })()
};
```

I'd rather not add a new rule each time I add a new page just to pass a different variable for `page`.

**Comment by mcmath** [comment]
I actually don't think there is a good solution to this that does not involve adding a rule for each page. This loader was initially designed with single-page apps in mind. I think you've identified a significant oversight on my part.

One solution would be to allow the user to pass a resource query where the template is required:

```js
import "./index.ejs?page=home";
```

For simple cases, the variable could be used directly:

```ejs
<html lang="en" ng-app="<%- page %>"></html>
```

For complex cases, the user could do something like this:

```js
{
  loader: "ejs-html-loader",
  options: {
    pages: {
      home: { app: "home-app", title: "Home Page", /* ... */ },
      about: { app: "about-app", title: "About Page", /* ... */ }
    }
  }
}
```

```ejs
// index.ejs
<html lang="en" ng-app="<%- pages[page].app %>">
  <h1><%- pages[page].title %></h1>
</html>
```

Would that solve your problem? Any input would be appreciated.

**Comment by mcmath** [comment]
I've implemented the above in `v3.1.0`. I'm not sure if this solves the issue, so I will leave it open for now.

**Comment by daniel-nagy** [comment]
Thanks! Using query parameters seems to be the way to go. However, now I have an issue with

```ejs
<%- include(template) %>
```

not reloading the browser when I make changes.

**Comment by mcmath** [comment]
Dynamic include statements won't recompile in watch mode. You have to use this syntax:

```ejs
<% include path/to/file.ejs %>
```

This is an issue that's come up before, and I've found it to be insoluble without writing a custom EJS parser. But there are workarounds. See Issue #7.
